<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20150312160636 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
		// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("CREATE TABLE passbin_base_domain_model_user (persistence_object_identifier VARCHAR(40) NOT NULL, account VARCHAR(40) DEFAULT NULL, firstname VARCHAR(255) NOT NULL, lastname VARCHAR(255) NOT NULL, lastlogin DATETIME NOT NULL, email VARCHAR(255) NOT NULL, resetid VARCHAR(255) NOT NULL, activated TINYINT(1) NOT NULL, UNIQUE INDEX UNIQ_D0EF57C97D3656A4 (account), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE passbin_base_domain_model_pass (persistence_object_identifier VARCHAR(40) NOT NULL, user VARCHAR(40) DEFAULT NULL, id VARCHAR(255) NOT NULL, creator VARCHAR(255) DEFAULT NULL, headline VARCHAR(255) NOT NULL, sendemail VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, password VARCHAR(255) NOT NULL, secure LONGTEXT NOT NULL, creationdate DATETIME NOT NULL, expiration DATETIME NOT NULL, callable INT NOT NULL, INDEX IDX_930C55A48D93D649 (user), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("ALTER TABLE passbin_base_domain_model_user ADD CONSTRAINT FK_D0EF57C97D3656A4 FOREIGN KEY (account) REFERENCES typo3_flow_security_account (persistence_object_identifier)");
		$this->addSql("ALTER TABLE passbin_base_domain_model_pass ADD CONSTRAINT FK_930C55A48D93D649 FOREIGN KEY (user) REFERENCES passbin_base_domain_model_user (persistence_object_identifier)");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
		// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE passbin_base_domain_model_pass DROP FOREIGN KEY FK_930C55A48D93D649");
		$this->addSql("DROP TABLE passbin_base_domain_model_user");
		$this->addSql("DROP TABLE passbin_base_domain_model_pass");
	}
}