<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20141211093607 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
		// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE passbin_base_domain_model_pass ADD user VARCHAR(40) DEFAULT NULL");
		$this->addSql("ALTER TABLE passbin_base_domain_model_pass ADD CONSTRAINT FK_930C55A48D93D649 FOREIGN KEY (user) REFERENCES passbin_base_domain_model_user (persistence_object_identifier)");
		$this->addSql("CREATE INDEX IDX_930C55A48D93D649 ON passbin_base_domain_model_pass (user)");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
		// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE passbin_base_domain_model_pass DROP FOREIGN KEY FK_930C55A48D93D649");
		$this->addSql("DROP INDEX IDX_930C55A48D93D649 ON passbin_base_domain_model_pass");
		$this->addSql("ALTER TABLE passbin_base_domain_model_pass DROP user");
	}
}