-
  name: 'Homepage'
  uriPattern: ''
  defaults:
    '@package': 'Passbin.Base'
    '@controller': 'CreatePass'
    '@action': 'new'

-
  name: 'ViewPass'
  uriPattern: 'id/{id}'
  defaults:
    '@package': 'Passbin.Base'
    '@controller': 'ViewPass'
    '@action': 'index'